/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fon.ai.maventransportappserver.server.forms;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import fon.ai.maventransportappserver.threads.ServerThread;

/**
 *
 * @author stackOverflow
 */
public class FServer extends javax.swing.JFrame {

    ServerThread serverThread;
    
    public FServer() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDisable = new javax.swing.JButton();
        jButtonEnable = new javax.swing.JButton();
        jButtonConfiguration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[FON] Serverski Program - Server Forma");

        jButtonDisable.setText("Disable");
        jButtonDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisableActionPerformed(evt);
            }
        });

        jButtonEnable.setText("Enable");
        jButtonEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnableActionPerformed(evt);
            }
        });

        jButtonConfiguration.setText("Configuration");
        jButtonConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigurationActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Server nije pokrenut!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEnable)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonDisable)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonConfiguration))
                    .addComponent(jLabel1))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDisable)
                    .addComponent(jButtonEnable)
                    .addComponent(jButtonConfiguration))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnableActionPerformed
         if (serverThread == null || !serverThread.isAlive()) {
            try {
                serverThread = new ServerThread();
                serverThread.start();
                jButtonEnable.setEnabled(false);
                jButtonDisable.setEnabled(true);
                jLabel1.setText("Server je pokrenut!");
                jLabel1.setForeground(Color.black);
            } catch (IOException ex) {
                Logger.getLogger(FServer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonEnableActionPerformed

    private void jButtonConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigurationActionPerformed
        JFrame jf;
        try {
            jf = new FConfigurations(this);
            jf.setVisible(true);
            setEnabled(false);
        } catch (IOException ex) {
            Logger.getLogger(FServer.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButtonConfigurationActionPerformed

    private void jButtonDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisableActionPerformed
        if (serverThread != null && serverThread.getServerSocket().isBound()) {
            try {
                serverThread.closeAllClientsThreads();
                serverThread.stopServerThread();
                jButtonEnable.setEnabled(true);
                jButtonDisable.setEnabled(false);
                jLabel1.setText("Server nije pokrenut!");
                jLabel1.setForeground(Color.red);
            } catch (Exception ex) {
                System.out.println("Server je zatvoren!");
            }
        }
    }//GEN-LAST:event_jButtonDisableActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfiguration;
    private javax.swing.JButton jButtonDisable;
    private javax.swing.JButton jButtonEnable;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
