/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fon.ai.maventransportappclient.client.forms;

import javax.swing.JFrame;

/**
 *
 * @author stackOverflow
 */
public class FMainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public FMainForm() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDrive = new javax.swing.JMenu();
        jMenuItemNewDrive = new javax.swing.JMenuItem();
        jMenuItemAnalyseDrive = new javax.swing.JMenuItem();
        jMenuDriver = new javax.swing.JMenu();
        jMenuItemNewDriver = new javax.swing.JMenuItem();
        jMenuVehicle = new javax.swing.JMenu();
        jMenuItemNewVehicle = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[FON] Client program - Main form");

        jMenuDrive.setText("Drive");

        jMenuItemNewDrive.setText("New");
        jMenuItemNewDrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewDriveActionPerformed(evt);
            }
        });
        jMenuDrive.add(jMenuItemNewDrive);

        jMenuItemAnalyseDrive.setText("SearchDrive");
        jMenuItemAnalyseDrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnalyseDriveActionPerformed(evt);
            }
        });
        jMenuDrive.add(jMenuItemAnalyseDrive);

        jMenuBar1.add(jMenuDrive);

        jMenuDriver.setText("Driver");

        jMenuItemNewDriver.setText("New");
        jMenuItemNewDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewDriverActionPerformed(evt);
            }
        });
        jMenuDriver.add(jMenuItemNewDriver);

        jMenuBar1.add(jMenuDriver);

        jMenuVehicle.setText("Vehicle");

        jMenuItemNewVehicle.setText("New");
        jMenuItemNewVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewVehicleActionPerformed(evt);
            }
        });
        jMenuVehicle.add(jMenuItemNewVehicle);

        jMenuBar1.add(jMenuVehicle);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNewDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewDriverActionPerformed
        JFrame d = new FDriver(this);
        d.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItemNewDriverActionPerformed

    private void jMenuItemNewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewVehicleActionPerformed
        JFrame v = new FVehicle(this);
        v.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItemNewVehicleActionPerformed

    private void jMenuItemAnalyseDriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnalyseDriveActionPerformed
        JFrame jf = new FDrivesSearch(this);
        jf.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItemAnalyseDriveActionPerformed

    private void jMenuItemNewDriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewDriveActionPerformed
        JFrame d = new FDrive(null, false, FDriveMode.NEW, null, this);
        d.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItemNewDriveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDrive;
    private javax.swing.JMenu jMenuDriver;
    private javax.swing.JMenuItem jMenuItemAnalyseDrive;
    private javax.swing.JMenuItem jMenuItemNewDrive;
    private javax.swing.JMenuItem jMenuItemNewDriver;
    private javax.swing.JMenuItem jMenuItemNewVehicle;
    private javax.swing.JMenu jMenuVehicle;
    // End of variables declaration//GEN-END:variables

    void omoguciIzmenu() {
        this.setEnabled(true);
    }
}
