/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fon.ai.maventransportappclient.client.forms;

import fon.ai.maventransportappclient.controller.CommunicationController;
import fon.ai.maventransportappcommon.domain.Trailer;
import fon.ai.maventransportappcommon.domain.Truck;
import fon.ai.maventransportappcommon.domain.Vehicle;
import fon.ai.maventransportappcommon.domain.VehicleType;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author stackOverflow
 */
public class FVehicle extends javax.swing.JFrame {
    FMainForm fmf;
    /**
     * Creates new form Vehicle
     * @param fmf
     */
    public FVehicle(FMainForm fmf) {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        srediKomponente();
        this.fmf = fmf;
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                fmf.setEnabled(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelBrand = new javax.swing.JLabel();
        jTextFieldBrand = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProductYear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRegistrationMark = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldWeight = new javax.swing.JTextField();
        jLabelTransmission = new javax.swing.JLabel();
        jLabelTrailerType = new javax.swing.JLabel();
        jLabelLoadCapacity = new javax.swing.JLabel();
        jComboBoxTrailerType = new javax.swing.JComboBox<>();
        jComboBoxTransmission = new javax.swing.JComboBox<>();
        jTextFieldLoadCapacity = new javax.swing.JTextField();
        jRadioButtonTruck = new javax.swing.JRadioButton();
        jRadioButtonTrailer = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adding new vehicle");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelBrand.setText("Brand:");

        jLabel1.setText("Product year:");

        jLabel2.setText("Registration mark:");

        jLabel3.setText("Weight: (kg)");

        jLabelTransmission.setText("Transmission:");

        jLabelTrailerType.setText("Trailer type:");

        jLabelLoadCapacity.setText("Load capacity: (kg)");

        jComboBoxTrailerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldLoadCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoadCapacityActionPerformed(evt);
            }
        });

        jRadioButtonTruck.setText("Truck");
        jRadioButtonTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTruckActionPerformed(evt);
            }
        });

        jRadioButtonTrailer.setText("Trailer");
        jRadioButtonTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTrailerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabelBrand))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldBrand)
                                .addComponent(jTextFieldProductYear)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldRegistrationMark)
                                .addComponent(jTextFieldWeight)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelTransmission)
                                .addComponent(jComboBoxTransmission, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 111, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonTrailer, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelLoadCapacity, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelTrailerType))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldLoadCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxTrailerType, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jRadioButtonTruck))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBrand)
                    .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProductYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldRegistrationMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTruck)
                    .addComponent(jRadioButtonTrailer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTrailerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrailerType)
                    .addComponent(jLabelTransmission))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLoadCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLoadCapacity)
                    .addComponent(jComboBoxTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if(jTextFieldBrand.getText().isEmpty() || jTextFieldProductYear.getText().isEmpty() || jTextFieldRegistrationMark.getText().isEmpty() || jTextFieldWeight.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti sve atribute vozila!");
            return;
        }
        String brand = jTextFieldBrand.getText();
        int productYear;
        try{
            productYear = (Integer.parseInt(jTextFieldProductYear.getText()));
            if(productYear > (Calendar.getInstance().get(Calendar.YEAR))){
                JOptionPane.showMessageDialog(this, "Godina proizvodnje je prirodan broj i mora biti pre sadasnje godine!");
                return;
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Godina proizvodnje je prirodan broj i mora biti pre sadasnje godine!");
            return;
        }
        
        String registrationMark = jTextFieldRegistrationMark.getText();
        double weight;
        try{
            weight = Double.parseDouble(jTextFieldWeight.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Tezina mora biti prirodan broj!");
            return;
        }
        if(weight< 0){
            JOptionPane.showMessageDialog(this, "Tezina mora biti prirodan broj!");
            return;
        }
        if(!jRadioButtonTruck.isSelected() && !jRadioButtonTrailer.isSelected()){
            JOptionPane.showMessageDialog(this, "Morate odabrati tip vozila!");
            return;
        }
        if(jRadioButtonTruck.isSelected()){
            String transmission = (String) jComboBoxTransmission.getSelectedItem();
            Vehicle truck = new Truck(transmission, brand, productYear, registrationMark, weight, "K");
            
            try {
                CommunicationController.getInstance().insertTruck(truck);
                JOptionPane.showMessageDialog(this, "Uspesno unesen kamiona u bazu!");
                fmf.omoguciIzmenu();
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspesan unos kamiona u bazu!");
        }
            
        }else{
            double loadCapacity;
            try{
                loadCapacity = Double.parseDouble(jTextFieldLoadCapacity.getText());
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Kapacitet prikolice mora da bude pozitivan realan broj");
                return;
            }
            if(loadCapacity < 0){
                JOptionPane.showMessageDialog(this, "Kapacitet prikolice mora da bude pozitivan realan broj");
                return;
            }
            VehicleType trailerType = (VehicleType.valueOf((jComboBoxTrailerType.getSelectedItem()).toString()));
            Vehicle trailer = new Trailer(trailerType, loadCapacity, brand, productYear, registrationMark, weight, "P");
            try {
                CommunicationController.getInstance().insertTrailer(trailer);
                fmf.omoguciIzmenu();
                JOptionPane.showMessageDialog(this, "Uspesno unesena prikolica u bazu!");
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspesno unosena prikolica u bazu!"); 
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
        fmf.omoguciIzmenu();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jRadioButtonTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTruckActionPerformed
        jComboBoxTransmission.setVisible(true);
        jLabelTransmission.setVisible(true);
        jComboBoxTrailerType.setVisible(false);
        jTextFieldLoadCapacity.setVisible(false);
        jLabelLoadCapacity.setVisible(false);
        jLabelTrailerType.setVisible(false);
    }//GEN-LAST:event_jRadioButtonTruckActionPerformed

    private void jRadioButtonTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTrailerActionPerformed
        jComboBoxTrailerType.setVisible(true);
        jTextFieldLoadCapacity.setVisible(true);
        jLabelLoadCapacity.setVisible(true);
        jLabelTrailerType.setVisible(true);
        jComboBoxTransmission.setVisible(false);
        jLabelTransmission.setVisible(false);
    }//GEN-LAST:event_jRadioButtonTrailerActionPerformed

    private void jTextFieldLoadCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoadCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoadCapacityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxTrailerType;
    private javax.swing.JComboBox<String> jComboBoxTransmission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBrand;
    private javax.swing.JLabel jLabelLoadCapacity;
    private javax.swing.JLabel jLabelTrailerType;
    private javax.swing.JLabel jLabelTransmission;
    private javax.swing.JRadioButton jRadioButtonTrailer;
    private javax.swing.JRadioButton jRadioButtonTruck;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldLoadCapacity;
    private javax.swing.JTextField jTextFieldProductYear;
    private javax.swing.JTextField jTextFieldRegistrationMark;
    private javax.swing.JTextField jTextFieldWeight;
    // End of variables declaration//GEN-END:variables

    private void srediKomponente() {
        jComboBoxTrailerType.removeAllItems();
        jComboBoxTrailerType.addItem(VehicleType.HLADNJACA.toString());
        jComboBoxTrailerType.addItem(VehicleType.CIRADA.toString());
        
        jComboBoxTransmission.removeAllItems();
        jComboBoxTransmission.addItem("MANUAL");
        jComboBoxTransmission.addItem("AUTOMATIC");
        
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButtonTrailer);
        group.add(jRadioButtonTruck);
        
        jComboBoxTransmission.setVisible(false);
        jLabelTransmission.setVisible(false);
        jComboBoxTrailerType.setVisible(false);
        jTextFieldLoadCapacity.setVisible(false);
        jLabelLoadCapacity.setVisible(false);
        jLabelTrailerType.setVisible(false);
    }
}
